export const DATA_SOURCE_TAG = 'DATA_SOURCE';

export const USER_REPOSITORY_TAG = 'USER_REPOSITORY';

export const ORGANIZATION_REPOSITORY_TAG = 'ORGANIZATION_REPOSITORY';

export const DEFAULT_HASHING_SALT = 10;
